name: Bug report
description: Report bugs with the mod here
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug here."
    validations:
      required: true

  - type: textarea
    id: systemdata
    attributes:
      label: "Information from the SystemData.txt in your VS FNaF 3 folder"
    validations:
      required: true

  - type: textarea
    id: crashlog
    attributes:
      label: "Information from the latest crashlog in your VS FNaF 3/crash folder"
    validations:
      required: false

  - type: dropdown
    id: consistency
    attributes:
      label: "Does the issue occur consistently?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: cachingmethod
    attributes:
      label: "Do you have 'Prefer GPU Caching' enabled in Graphics settings?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: cachingmethod
    attributes:
      label: "Do you have 'Shaders' enabled in Graphics settings?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
